DO $$
BEGIN
  CREATE TYPE "AdminType" AS ENUM ('BOOST_REQUEST', 'SUPPORT_ADMIN', 'OTHER_ADMIN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "admin_type" "AdminType" NOT NULL DEFAULT 'OTHER_ADMIN';
