export interface CategoryData {
  slug: string;
  title: string;
  description: string;
  color: string;
  services: string[];
}

export const categoryData: CategoryData[] = [
  {
    slug: 'digital-marketing',
    title: 'Digital Marketing Services',
    description: 'Comprehensive digital marketing solutions to grow your online presence and drive results.',
    color: 'bg-green-50',
    services: [
      'Facebook & Instagram Ads Management',
      'LinkedIn & TikTok Marketing',
      'Google Ads & Performance Max',
      'YouTube Ads Management',
      'SEO Optimization & Link Building',
      'Technical SEO Audit',
      'Local SEO & Google My Business',
      'Content Marketing & Blog Writing',
      'Email Marketing Campaigns',
      'Marketing Automation Setup',
      'Google Analytics & Conversion Tracking',
      'ROI Analysis & Reporting',
    ],
  },
  {
    slug: 'graphics-design',
    title: 'Graphics Design Services',
    description: 'Creative design solutions that make your brand stand out and communicate effectively.',
    color: 'bg-purple-50',
    services: [
      'Logo Design & Brand Identity',
      'Business Card & Stationery',
      'Social Media Graphics',
      'Digital Ad Banners & Animations',
      'Brochure & Flyer Design',
      'Product Packaging Design',
      'Presentation Design',
      'Infographic Design',
      'Print Design (Posters, Catalogs)',
      'Illustration & Character Design',
      'Motion Graphics & Logo Animation',
      'Photo Editing & Retouching',
    ],
  },
  {
    slug: 'software-development',
    title: 'Software Development Services',
    description: 'Custom software solutions tailored to your business needs and workflows.',
    color: 'bg-blue-50',
    services: [
      'Custom Web Applications',
      'CRM & ERP Systems',
      'Inventory Management Systems',
      'POS & Booking Systems',
      'SaaS Platform Development',
      'Multi-tenant Applications',
      'API Development & Integration',
      'E-commerce Solutions',
      'Payment Gateway Integration',
      'Multi-vendor Marketplaces',
      'Business Intelligence Tools',
      'Workflow Automation',
    ],
  },
  {
    slug: 'web-development',
    title: 'Web Development Services',
    description: 'Professional websites that are fast, responsive, and optimized for conversions.',
    color: 'bg-cyan-50',
    services: [
      'Corporate & E-commerce Websites',
      'Landing Page Development',
      'Portfolio & Blog Websites',
      'React.js & Next.js Development',
      'Vue.js & Angular Development',
      'Node.js Backend Development',
      'PHP/Laravel Development',
      'WordPress & WooCommerce',
      'Shopify & Magento Development',
      'Progressive Web Apps (PWA)',
      'RESTful & GraphQL API',
      'Website Maintenance & Support',
    ],
  },
  {
    slug: 'mobile-app-development',
    title: 'Mobile App Development',
    description: 'Native and cross-platform mobile apps that deliver exceptional user experiences.',
    color: 'bg-pink-50',
    services: [
      'iOS App Development (Swift)',
      'Android App Development (Kotlin)',
      'React Native Development',
      'Flutter Development',
      'E-commerce Mobile Apps',
      'Food Delivery Apps',
      'Social Networking Apps',
      'Healthcare & Education Apps',
      'App Store Optimization (ASO)',
      'Push Notification Setup',
      'Payment Gateway Integration',
      'App Maintenance & Updates',
    ],
  },
  {
    slug: 'ui-ux-design',
    title: 'UI/UX Design Services',
    description: 'User-centered design that creates intuitive and engaging digital experiences.',
    color: 'bg-orange-50',
    services: [
      'Website & App UI Design',
      'Dashboard & Admin Panel Design',
      'User Research & Analysis',
      'Wireframing & Prototyping',
      'User Journey Mapping',
      'Usability Testing',
      'Design System Creation',
      'Component Library',
      'Figma & Adobe XD Design',
      'Interactive Prototypes',
      'Accessibility Design (WCAG)',
      'Design Documentation',
    ],
  },
  {
    slug: 'branding-creative',
    title: 'Branding & Creative Services',
    description: 'Build a memorable brand identity that resonates with your target audience.',
    color: 'bg-yellow-50',
    services: [
      'Brand Strategy & Positioning',
      'Brand Messaging & Voice',
      'Competitor Analysis',
      'Logo Design & Redesign',
      'Brand Guidelines & Style Guide',
      'Color Palette Development',
      'Typography Selection',
      'Business Presentation Design',
      'Company Profile Design',
      'Marketing Collateral',
      'Corporate Gifts Design',
      'Brand Asset Library',
    ],
  },
  {
    slug: 'video-animation',
    title: 'Video & Animation Services',
    description: 'Engaging video content and animations that tell your story effectively.',
    color: 'bg-red-50',
    services: [
      'Corporate Video Production',
      'Product Demo Videos',
      'Explainer Videos',
      'Testimonial Videos',
      'Social Media Videos',
      'Video Editing & Color Grading',
      '2D & 3D Animation',
      'Whiteboard Animation',
      'Character Animation',
      'Motion Graphics',
      'Logo Animation',
      'Drone Videography',
    ],
  },
  {
    slug: 'business-consulting',
    title: 'Business Consulting Services',
    description: 'Strategic guidance to help your business grow and achieve digital transformation.',
    color: 'bg-indigo-50',
    services: [
      'Digital Transformation Consulting',
      'Technology Stack Selection',
      'Digital Marketing Strategy',
      'Growth Hacking Strategy',
      'Requirements Gathering',
      'Process Optimization',
      'Market Research & Feasibility',
      'ROI Analysis',
      'Team Training Sessions',
      'Software Training Workshops',
      'Technical Documentation',
      'Change Management Support',
    ],
  },
  {
    slug: 'specialized-services',
    title: 'Specialized Services',
    description: 'Advanced technical services for complex integrations and optimizations.',
    color: 'bg-teal-50',
    services: [
      'Payment Gateway Integration',
      'Social Media API Integration',
      'SMS & Email Service Setup',
      'CRM Integration (Salesforce, HubSpot)',
      'AWS & Cloud Platform Setup',
      'DevOps & CI/CD Pipeline',
      'SSL Certificate & Security Audit',
      'Website Speed Optimization',
      'Database Optimization',
      'CDN Setup (Cloudflare)',
      'Multi-currency & Multi-language',
      'Live Chat Integration',
    ],
  },
];
